### ISSUE TITLE
x86_64-elf-gcc install fails on Sierra

### ISSUE THREAD

**Issue by necktwi** [Harvey-OS/harvey#322]
#### Actual behavior

```
$ sudo brew install sevki/gcc_cross_compilers/x86_64-elf-gcc
Password:
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
==> Installing x86_64-elf-gcc from sevki/gcc_cross_compilers
==> Installing dependencies for sevki/gcc_cross_compilers/x86_64-elf-gcc: 
==> Installing sevki/gcc_cross_compilers/x86_64-elf-gcc dependency: xz
==> Downloading https://fossies.org/linux/misc/xz-5.2.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/xz-5.2.2.tar.gz
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/xz/5.2.2
Last 15 lines from /Users/gowtham/Library/Logs/Homebrew/xz/01.configure:
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether ln -s works... yes
checking for style of include used by make... GNU
checking for gcc... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/private/tmp/xz20161010-6556-guurh7/xz-5.2.2':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details

READ THIS: https://git.io/brew-troubleshooting

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:353:in `open_http': 422 Unprocessable Entity (GitHub::Error)
Validation Failed
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:709:in `buffer_open'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:210:in `block in open_loop'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `catch'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `open_loop'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:149:in `open_uri'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:689:in `open'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:30:in `open'
    from /usr/local/Library/Homebrew/utils.rb:523:in `open'
    from /usr/local/Library/Homebrew/utils.rb:554:in `issues_matching'
    from /usr/local/Library/Homebrew/utils.rb:586:in `issues_for_formula'
    from /usr/local/Library/Homebrew/exceptions.rb:222:in `fetch_issues'
    from /usr/local/Library/Homebrew/exceptions.rb:218:in `issues'
    from /usr/local/Library/Homebrew/exceptions.rb:263:in `dump'
    from /usr/local/Library/brew.rb:132:in `rescue in <main>'
    from /usr/local/Library/brew.rb:28:in `<main>'

```
#### Steps to reproduce
- Open terminal in macOS Sierra
- `$ sudo brew tap sevki/gcc_cross_compilers`
- `$ sudo brew install sevki/gcc_cross_compilers/x86_64-elf-gcc`

**Comment by elbing** [comment]
volunteers for building the cross toolchain for macOS Sierra?

**Comment by necktwi** [comment]
https://github.com/sevki/homebrew-gcc_cross_compilers is in `build failing` state. I tried to build on my mac; It fired up all the processors on my mac for 30min and finally failed!

**Comment by rminnich** [comment]
can you give us a bit more info that "it did not work" :-)

**Comment by necktwi** [comment]
```
$ brew install sevki/gcc_cross_compilers/x86_64-elf-gcc
==> Installing x86_64-elf-gcc from sevki/gcc_cross_compilers
Error: Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/sevki/homebrew-gcc_cross_compilers/x86_64-elf-binutils.rb:6:in `<class:X8664ElfBinutils>'
Please report this to the sevki/gcc_cross_compilers tap!
Please report this bug:
  https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Homebrew/utils.rb:86:in `odeprecated'
/usr/local/Homebrew/Library/Homebrew/utils.rb:94:in `odisabled'
/usr/local/Homebrew/Library/Homebrew/compat/sha1.rb:3:in `sha1'
/usr/local/Homebrew/Library/Taps/sevki/homebrew-gcc_cross_compilers/x86_64-elf-binutils.rb:6:in `<class:X8664ElfBinutils>'
/usr/local/Homebrew/Library/Taps/sevki/homebrew-gcc_cross_compilers/x86_64-elf-binutils.rb:3:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:97:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:240:in `factory'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:32:in `to_formula'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:93:in `block in expand'
/usr/local/Homebrew/Library/Homebrew/dependencies.rb:9:in `each'
/usr/local/Homebrew/Library/Homebrew/dependencies.rb:9:in `each'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:80:in `expand'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1447:in `recursive_dependencies'
/usr/local/Homebrew/Library/Homebrew/requirement.rb:200:in `expand'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1453:in `recursive_requirements'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:358:in `expand_requirements'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:307:in `compute_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:133:in `verify_deps_exist'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:126:in `prelude'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:265:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:161:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:161:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:161:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'

```
I didn't understand it. I wish could dig in to it!

**Comment by sevki** [comment]
ok, this doesn't belong here. it belongs in [sevki/homebrew-gcc_cross_compilers](https://github.com/sevki/homebrew-gcc_cross_compilersl). It' is now fixed, the [fix](https://github.com/sevki/homebrew-gcc_cross_compilers/compare/efbf478360aaa555e0747c04923d0f58a72c5333...sevki:23315c836bb0d0e745b3809cee0be8d7dd46f160) wasn't that complicated. And please do not post issued related to cross compilers here.
